"""Native EVE map data: loads the bundled ``data/eve_map.json`` (region layouts +
stargate graph + security, generated by ``gen_eve_map.py``) and provides region
layouts, system lookup, and stargate routing. Live layers (jumps/kills/sov) are
fetched in server.py; this module is pure static topology.
"""
import heapq
import json
import os
from functools import lru_cache

DATA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'eve_map.json')


@lru_cache(maxsize=1)
def load_map(path=DATA_PATH):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


@lru_cache(maxsize=1)
def _adjacency():
    """{sid(str): set(neighbour sid)} over the whole cluster."""
    adj = {}
    for a, b in load_map()['edges']:
        adj.setdefault(a, set()).add(b)
        adj.setdefault(b, set()).add(a)
    return adj


@lru_cache(maxsize=1)
def _name_index():
    """lowercased system name -> sid(str)."""
    return {rec['name'].lower(): sid for sid, rec in load_map()['systems'].items()}


def regions():
    d = load_map()
    return [{'id': r['id'], 'name': r['name'], 'count': len(r['systems'])} for r in d['regions']]


def region_layout(name):
    """Nodes (home + border adjacents, positioned in this region's Dotlan layout)
    and the region's jump lines. Returns None if the region isn't known."""
    d = load_map()
    lay = d['layouts'].get(name)
    if not lay:
        return None
    systems = d['systems']
    home = set(lay['home'])
    nodes = []
    for sid, xy in lay['pos'].items():
        rec = systems.get(sid, {})
        # Prefer the canonical name (every node is a home member of some region we
        # parsed); the per-layout label is only a fallback for the rare adjacent
        # in an unparsed region.
        nodes.append({
            'id': int(sid),
            'name': (rec.get('name') or lay.get('names', {}).get(sid) or sid),
            'x': xy[0], 'y': xy[1],
            'sec': rec.get('sec'),
            'home': sid in home,
            'region': rec.get('region') or lay.get('foreign', {}).get(sid),
        })
    return {'name': name, 'systems': nodes, 'edges': lay['edges']}


def resolve_system(token):
    """A system name or numeric id -> sid(str), or None."""
    s = str(token).strip()
    if not s:
        return None
    d = load_map()
    if s.isdigit():
        return s if s in d['systems'] else None
    return _name_index().get(s.lower())


def system_brief(sid):
    d = load_map()
    rec = d['systems'].get(str(sid))
    if not rec:
        return None
    return {'id': int(sid), 'name': rec['name'], 'region': rec.get('region'), 'sec': rec.get('sec')}


def system_detail(sid):
    """A system plus its directly-connected neighbours (for the detail panel)."""
    sid = str(sid)
    brief = system_brief(sid)
    if not brief:
        return None
    d = load_map()
    neigh = []
    for nb in sorted(_adjacency().get(sid, ()), key=int):
        rec = d['systems'].get(nb)
        if rec:
            neigh.append({'id': int(nb), 'name': rec['name'], 'region': rec.get('region'), 'sec': rec.get('sec')})
    brief['adjacent'] = neigh
    return brief


def _sec_band(sec):
    if sec is None:
        return 'null'
    return 'high' if sec >= 0.45 else ('low' if sec > 0.0 else 'null')


def route(src, dst, prefer='shortest'):
    """Stargate route from src to dst (names or ids). ``prefer``:
    ``shortest`` (fewest jumps), ``safe`` (prefer high-sec), ``unsafe`` (prefer
    low/null). Returns {jumps, systems:[{id,name,region,sec}]} or {error}."""
    a, b = resolve_system(src), resolve_system(dst)
    if not a:
        return {'error': f'Unknown system: {src}'}
    if not b:
        return {'error': f'Unknown system: {dst}'}
    d = load_map()
    systems = d['systems']
    adj = _adjacency()
    if a == b:
        return {'jumps': 0, 'systems': [system_brief(a)]}

    def weight(sid):
        if prefer == 'shortest':
            return 1
        band = _sec_band(systems.get(sid, {}).get('sec'))
        if prefer == 'safe':
            return 1 if band == 'high' else 5000
        if prefer == 'unsafe':
            return 1 if band in ('low', 'null') else 5000
        return 1

    # Dijkstra (weights collapse to BFS when prefer == shortest).
    dist = {a: 0}
    prev = {}
    pq = [(0, a)]
    while pq:
        cost, u = heapq.heappop(pq)
        if u == b:
            break
        if cost > dist.get(u, float('inf')):
            continue
        for v in adj.get(u, ()):
            nc = cost + weight(v)
            if nc < dist.get(v, float('inf')):
                dist[v] = nc
                prev[v] = u
                heapq.heappush(pq, (nc, v))
    if b not in prev and a != b:
        return {'error': 'No stargate route (systems may be in disconnected space, e.g. wormhole/Pochven).'}
    path = [b]
    while path[-1] != a:
        path.append(prev[path[-1]])
    path.reverse()
    return {'jumps': len(path) - 1, 'prefer': prefer, 'systems': [system_brief(s) for s in path]}
