"""Production-planner engine — multi-tier manufacturing + reaction BOM explosion.

Modelled on pi.py / refining.py: a bundled static dataset (data/industry.json,
generated by gen_industry_data.py) plus pure functions with no network IO. The
caller (server.py) supplies prices and industry config; this module only turns
"build N of X (given this stock)" into the jobs to run and the raw materials to
buy, applying ME and whole-run rounding exactly like the game.

Key model:
  * A *recipe* maps a product type -> {activity (manufacturing|reaction),
    output_qty per run, per-run material list, run time, max runs/job}.
  * A type is *buildable* if it has a recipe and the caller didn't force it onto
    the buy list; otherwise it's a *leaf* (raw material to purchase).
  * `plan()` walks the demand graph in topological order (a consumer is fully
    tallied before the thing it consumes), so shared sub-components aggregate
    into one job and per-job rounding is applied once at the real total.

ME formula (per CCP): for a job of `runs` runs and per-run base quantity `b`,
  required = max(runs, ceil(round(b * runs * material_multiplier, 2)))
where material_multiplier = (1 - ME/100) * structure_material_mult for
manufacturing, or reaction_material_mult for reactions (reactions ignore ME).
"""
import json
import math
import os
import sys
from functools import lru_cache


def _bundled_data_path(name):
    """data/<name> — the PyInstaller extraction dir when frozen, else next to
    this module in dev. Mirrors pi._bundled_data_path."""
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base, 'data', name)


DATA_PATH = _bundled_data_path('industry.json')

MANUFACTURING = 'manufacturing'
REACTION = 'reaction'
INVENTION = 'invention'

# T2 blueprints come out of invention at a fixed base ME/TE (2/4) before any
# decryptor modifier — used to price the manufacturing step of invented items.
T2_INVENTED_ME = 2

# The eight invention decryptors: probability multiplier, ME / TE / run modifiers,
# and the item type_id (for pricing). ``None`` = invent with no decryptor.
DECRYPTORS = {
    'None': {'type_id': None, 'name': None, 'prob': 1.0, 'me': 0, 'te': 0, 'runs': 0},
    'Accelerant': {'type_id': 34201, 'name': 'Accelerant Decryptor', 'prob': 1.2, 'me': 2, 'te': 10, 'runs': 1},
    'Attainment': {'type_id': 34203, 'name': 'Attainment Decryptor', 'prob': 1.8, 'me': -1, 'te': 4, 'runs': 4},
    'Augmentation': {'type_id': 34204, 'name': 'Augmentation Decryptor', 'prob': 0.6, 'me': -2, 'te': 2, 'runs': 9},
    'Optimized Attainment': {'type_id': 34207, 'name': 'Optimized Attainment Decryptor', 'prob': 1.9, 'me': 1, 'te': -2, 'runs': 2},
    'Optimized Augmentation': {'type_id': 34208, 'name': 'Optimized Augmentation Decryptor', 'prob': 0.9, 'me': 2, 'te': 0, 'runs': 7},
    'Parity': {'type_id': 34205, 'name': 'Parity Decryptor', 'prob': 1.5, 'me': 1, 'te': -2, 'runs': 3},
    'Process': {'type_id': 34206, 'name': 'Process Decryptor', 'prob': 1.1, 'me': 3, 'te': 6, 'runs': 0},
    'Symmetry': {'type_id': 34202, 'name': 'Symmetry Decryptor', 'prob': 1.0, 'me': 1, 'te': 8, 'runs': 2},
}


def invention_skill_factor(level):
    """Success-chance multiplier from the three invention skills all at ``level``:
    Encryption Methods contributes level/40, the two datacore science skills
    2*level/30. (level 4 -> 1.367, level 5 -> 1.458.)"""
    lvl = max(0, min(5, int(level)))
    return 1.0 + lvl / 40.0 + 2.0 * lvl / 30.0


@lru_cache(maxsize=1)
def load_industry_data(path=DATA_PATH):
    """Load + index the bundled industry dataset. Cached. Returns a dict with:

      recipes    {product_type_id(int): recipe}
      types      {type_id(int): {name, group_id, group_name, category_id, meta_group_id}}
      by_name    {lowercased type name: type_id}  (buildable + material types)
      tiers      {type_id(int): int}   0 = raw leaf; else 1 + max(material tiers)
    """
    with open(path, encoding='utf-8') as f:
        raw = json.load(f)
    return index_data(raw)


def index_data(raw):
    """Index a raw dataset dict ({recipes, types}) into the runtime shape. Split
    out from load_industry_data so tests can build a synthetic dataset in memory."""
    recipes = {int(k): v for k, v in raw['recipes'].items()}
    types = {int(k): v for k, v in raw['types'].items()}
    invention = {int(k): v for k, v in (raw.get('invention') or {}).items()}
    # Decryptors aren't blueprint materials, so they're absent from the generated
    # type map — inject them so they price and display by name in the buy list.
    for decr in DECRYPTORS.values():
        if decr['type_id'] and decr['type_id'] not in types:
            types[decr['type_id']] = {'name': decr['name'], 'group_id': None,
                                      'group_name': 'Decryptor', 'category_id': None,
                                      'meta_group_id': None}
    by_name = {}
    for tid, meta in types.items():
        nm = (meta.get('name') or '').strip().lower()
        if nm and nm not in by_name:
            by_name[nm] = tid
    tiers = _compute_tiers(recipes)
    # Invention is keyed by the T2 *blueprint* id; join it to the manufactured
    # *item* via each recipe's blueprint_type_id so a plan can look it up by item.
    invention_by_item = {}
    for item_id, recipe in recipes.items():
        rec = invention.get(recipe.get('blueprint_type_id'))
        if rec:
            invention_by_item[item_id] = rec
    return {'recipes': recipes, 'types': types, 'by_name': by_name, 'tiers': tiers,
            'invention': invention, 'invention_by_item': invention_by_item}


def _compute_tiers(recipes):
    """tier(type) = 0 for a leaf (no recipe), else 1 + max(tier(material)).
    Memoised DFS over the recipe DAG (EVE industry has no cycles)."""
    tiers = {}

    def tier(tid, stack):
        if tid in tiers:
            return tiers[tid]
        r = recipes.get(tid)
        if not r:
            tiers[tid] = 0
            return 0
        if tid in stack:  # defensive — shouldn't happen
            tiers[tid] = 0
            return 0
        stack = stack | {tid}
        t = 1 + max((tier(m[0], stack) for m in r['materials']), default=0)
        tiers[tid] = t
        return t

    for pid in recipes:
        tier(pid, frozenset())
    return tiers


def type_name(type_id, data=None):
    data = data or load_industry_data()
    t = data['types'].get(int(type_id))
    return t['name'] if t else f'type {type_id}'


def resolve_type(token, data=None):
    """Resolve a target token (numeric type_id or a type name) to an int type_id,
    or None. Name match is case-insensitive, exact after trim."""
    data = data or load_industry_data()
    s = str(token).strip()
    if not s:
        return None
    if s.isdigit():
        tid = int(s)
        return tid if tid in data['types'] or tid in data['recipes'] else tid
    return data['by_name'].get(s.lower())


def parse_targets(text, data=None):
    """Parse a pasted target list into [{type_id, name, qty, unresolved}].

    Accepts one entry per line: ``Name xN``, ``Name    N`` (tab/space + trailing
    integer), or a bare ``Name`` (qty 1). Unresolved names are returned flagged
    so the UI can surface them."""
    data = data or load_industry_data()
    out = []
    for raw_line in (text or '').splitlines():
        line = raw_line.strip()
        if not line:
            continue
        name, qty = _split_qty(line)
        tid = resolve_type(name, data)
        if tid is None:
            out.append({'type_id': None, 'name': name, 'qty': qty, 'unresolved': True})
        else:
            out.append({'type_id': tid, 'name': type_name(tid, data), 'qty': qty, 'unresolved': False})
    return out


def _split_qty(line):
    """(name, qty) from one line. 'Ravana x3' / 'Ravana\\t3' / 'Ravana' -> qty."""
    low = line.lower()
    # "name xN"
    xi = low.rfind(' x')
    if xi != -1:
        tail = line[xi + 2:].strip().replace(',', '').replace('.', '')
        if tail.isdigit():
            return line[:xi].strip(), max(1, int(tail))
    # tab- or multi-space-separated trailing integer
    parts = line.replace('\t', '    ').rsplit('  ', 1)
    if len(parts) == 2:
        tail = parts[1].strip().replace(',', '').replace('.', '')
        if tail.isdigit():
            return parts[0].strip(), max(1, int(tail))
    return line, 1


def _material_required(base_qty, runs, multiplier):
    """CCP material rounding: max(runs, ceil(round(base*runs*mult, 2)))."""
    if base_qty <= 0 or runs <= 0:
        return 0
    scaled = round(base_qty * runs * multiplier, 2)
    return max(runs, math.ceil(scaled))


def plan(targets, stock=None, config=None, data=None):
    """Explode a build request into jobs + a raw shopping list.

    targets: [{type_id, qty}] — what to end up with.
    stock:   {type_id: qty} — on-hand items (products or materials) that offset
             demand before anything is built/bought.
    config:  {me, structure_material_mult, reaction_material_mult, buy_ids,
              max_depth} — all optional.

    Returns {jobs, raw_materials, targets, warnings} where:
      jobs          [{type_id, name, activity, runs, output_qty, produced,
                      blueprint_type_id, time_per_run, total_time, tier}]
                    sorted ascending by tier (build order: components first).
      raw_materials [{type_id, name, qty}] sorted by name — the buy list.
    """
    data = data or load_industry_data()
    recipes = data['recipes']
    tiers = data['tiers']
    invention_by_item = data.get('invention_by_item', {})
    cfg = config or {}
    me = float(cfg.get('me', 10) or 0)
    struct_mult = float(cfg.get('structure_material_mult', 1.0) or 1.0)
    rx_mult = float(cfg.get('reaction_material_mult', 1.0) or 1.0)
    buy_ids = set(int(x) for x in (cfg.get('buy_ids') or []))
    max_depth = int(cfg.get('max_depth', 64) or 64)
    invent = bool(cfg.get('invention', True))
    decryptor = DECRYPTORS.get(cfg.get('decryptor') or 'None', DECRYPTORS['None'])
    skill_factor = invention_skill_factor(cfg.get('invention_skill_level', 4))

    stock = {int(k): float(v) for k, v in (stock or {}).items()}
    stock_left = dict(stock)
    warnings = []
    inv_jobs = []
    inv_input_ids = set()   # datacore / decryptor type_ids (for cost breakdown)

    def will_build(tid):
        return tid in recipes and tid not in buy_ids

    def is_invented(tid):
        return invent and tid in invention_by_item

    def mat_multiplier(node, activity):
        if activity == MANUFACTURING:
            # Invented (T2) items build off the invented BPC's ME (base 2 +
            # decryptor), not the researched-BPO ME the caller sets globally.
            eff_me = max(0.0, T2_INVENTED_ME + decryptor['me']) if is_invented(node) else me
            return max(0.0, (100.0 - eff_me) / 100.0) * struct_mult
        return rx_mult  # reactions ignore ME

    def consume_leaf(tid, qty):
        """Offset a pure-leaf demand (invention datacore/decryptor) against stock,
        adding the remainder to the raw buy list."""
        have = stock_left.get(tid, 0)
        if have:
            used = min(have, qty)
            stock_left[tid] = have - used
            qty -= used
        if qty > 0:
            raw[tid] = raw.get(tid, 0) + qty

    def add_invention(node, mfg_runs):
        """Model inventing the T2 BPC that the manufacturing job consumes: expected
        attempts, datacores, and (optional) decryptor at the given probability."""
        rec = invention_by_item[node]
        runs_per_copy = max(1, rec['output_runs'] + decryptor['runs'])
        successes = math.ceil(mfg_runs / runs_per_copy)
        prob = min(1.0, max(1e-6, rec['probability'] * decryptor['prob'] * skill_factor))
        attempts = successes / prob
        for dc_id, dc_qty in rec['datacores']:
            consume_leaf(dc_id, math.ceil(attempts * dc_qty))
            inv_input_ids.add(dc_id)
        if decryptor['type_id']:
            consume_leaf(decryptor['type_id'], math.ceil(attempts))
            inv_input_ids.add(decryptor['type_id'])
        inv_jobs.append({
            'type_id': node,
            'name': type_name(node, data),
            'activity': INVENTION,
            'runs': math.ceil(attempts),          # expected invention attempts
            'output_qty': runs_per_copy,
            'produced': successes,                 # BPCs needed
            'probability': prob,
            'decryptor': None if decryptor['type_id'] is None else next(
                (k for k, v in DECRYPTORS.items() if v is decryptor), 'None'),
            'tier': tiers.get(node, 0) + 0.5,      # sits just above its build step
        })

    # Aggregate external demand from the targets, then resolve in topo order.
    demand = {}
    for t in targets:
        tid = t.get('type_id')
        if tid is None:
            continue
        demand[int(tid)] = demand.get(int(tid), 0) + max(0, int(t.get('qty') or 0))

    # Build the reachable build-subgraph so we can order consumers before
    # producers. Only edges through *will_build* nodes matter.
    reachable = set(demand)
    stack = list(demand)
    while stack:
        n = stack.pop()
        if will_build(n):
            for m in recipes[n]['materials']:
                if m[0] not in reachable:
                    reachable.add(m[0])
                    stack.append(m[0])

    # Kahn topological sort: in_degree(n) = number of will_build consumers of n
    # within the subgraph. Process a node only once all its consumers are done.
    in_degree = {n: 0 for n in reachable}
    for n in reachable:
        if will_build(n):
            for m in recipes[n]['materials']:
                if m[0] in in_degree:
                    in_degree[m[0]] += 1
    queue = [n for n in reachable if in_degree[n] == 0]

    jobs = {}
    raw = {}
    processed = 0
    while queue:
        # Deepest-consumer-first isn't required; Kahn guarantees correctness.
        node = queue.pop()
        processed += 1
        need = demand.get(node, 0)
        have = stock_left.get(node, 0)
        if have:
            used = min(have, need)
            stock_left[node] = have - used
            need -= used
        if need > 0:
            if will_build(node):
                r = recipes[node]
                out_qty = r['output_qty'] or 1
                runs = math.ceil(need / out_qty)
                produced = runs * out_qty
                mult = mat_multiplier(node, r['activity'])
                jobs[node] = {
                    'type_id': node,
                    'name': type_name(node, data),
                    'activity': r['activity'],
                    'runs': runs,
                    'output_qty': out_qty,
                    'produced': produced,
                    'invented': is_invented(node),
                    'blueprint_type_id': r.get('blueprint_type_id'),
                    'time_per_run': r.get('time') or 0,
                    'total_time': (r.get('time') or 0) * runs,
                    'tier': tiers.get(node, 0),
                }
                for mat_id, base_qty in r['materials']:
                    demand[mat_id] = demand.get(mat_id, 0) + _material_required(base_qty, runs, mult)
                if is_invented(node):
                    add_invention(node, runs)
            else:
                raw[node] = raw.get(node, 0) + need
        # Release consumers -> producers.
        if will_build(node):
            for m in recipes[node]['materials']:
                if m[0] in in_degree:
                    in_degree[m[0]] -= 1
                    if in_degree[m[0]] == 0:
                        queue.append(m[0])

    if processed < len(reachable):
        warnings.append('dependency graph did not fully resolve (possible data cycle)')

    # ---- Production tree (per-branch recipe decomposition) ----
    # A hierarchical view: each target expands into the materials its own build
    # consumes (post-ME, whole-run rounded), recursively, down to raw/bought
    # leaves. Honors the same buy/ME/invention config as the flat plan; ignores
    # stock (it's a structural view — the jobs/shopping list carry the net
    # numbers). Node-capped so a deep capital tree can't blow up the payload.
    tree = []
    if bool(cfg.get('include_tree', True)):
        node_budget = [int(cfg.get('tree_node_cap', 4000) or 4000)]
        truncated_tree = [False]

        def _node(tid, qty, path):
            node_budget[0] -= 1
            r = recipes.get(tid)
            node = {'type_id': tid, 'name': type_name(tid, data), 'qty': int(math.ceil(qty))}
            if not r or tid in buy_ids:
                node['activity'] = 'buy' if (r and tid in buy_ids) else 'raw'
                node['invention_input'] = tid in inv_input_ids
                return node
            out_qty = r['output_qty'] or 1
            runs = math.ceil(qty / out_qty)
            node.update(activity=r['activity'], runs=runs, output_qty=out_qty, produced=runs * out_qty)
            if is_invented(tid):
                rec = invention_by_item[tid]
                node['invented'] = True
                node['probability'] = min(1.0, max(1e-6, rec['probability'] * decryptor['prob'] * skill_factor))
            if node_budget[0] > 0 and tid not in path:
                mult = mat_multiplier(tid, r['activity'])
                node['children'] = [_node(m[0], _material_required(m[1], runs, mult), path | {tid})
                                    for m in r['materials']]
            else:
                node['truncated'] = True
                truncated_tree[0] = True
            return node

        root_demand = {}
        for t in targets:
            root_demand[t['type_id']] = root_demand.get(t['type_id'], 0) + max(0, int(t.get('qty') or 0))
        tree = [_node(tid, qty, frozenset()) for tid, qty in root_demand.items()]
        if truncated_tree[0]:
            warnings.append('production tree truncated (very large build) — jobs/shopping list are complete')

    jobs_out = sorted(list(jobs.values()) + inv_jobs, key=lambda j: (j['tier'], j['name']))
    raw_out = sorted(
        ({'type_id': tid, 'name': type_name(tid, data), 'qty': int(q),
          'invention': tid in inv_input_ids,
          # A raw row that *has* a recipe is only here because it was forced onto
          # the buy list — flag it so the UI can offer a "build instead" toggle.
          'buildable': tid in recipes} for tid, q in raw.items() if q > 0),
        key=lambda r: r['name'],
    )
    # Compact per-type metadata (display name + market group) for every distinct
    # type in the plan, so the chain-flow UI can name and *categorise* nodes —
    # including raw materials that have no recipe (ore, moon goo, PI, minerals) —
    # without any extra look-ups.
    def _collect_ids(node, acc):
        if node.get('type_id') is not None:
            acc.add(int(node['type_id']))
        for c in node.get('children') or []:
            _collect_ids(c, acc)

    meta_ids = {j['type_id'] for j in jobs_out if j.get('type_id') is not None}
    meta_ids |= {r['type_id'] for r in raw_out if r.get('type_id') is not None}
    for root in tree:
        _collect_ids(root, meta_ids)
    type_meta = {}
    for tid in meta_ids:
        m = data['types'].get(int(tid)) or {}
        type_meta[int(tid)] = {'name': m.get('name') or type_name(tid, data),
                               'group': m.get('group_name')}

    return {
        'jobs': jobs_out,
        'raw_materials': raw_out,
        'tree': tree,
        'type_meta': type_meta,
        'invention': {
            'enabled': invent,
            'decryptor': cfg.get('decryptor') or 'None',
            'skill_level': int(cfg.get('invention_skill_level', 4)),
            'job_count': len(inv_jobs),
            'total_attempts': sum(j['runs'] for j in inv_jobs),
        },
        'targets': [{'type_id': t.get('type_id'), 'name': type_name(t['type_id'], data)
                     if t.get('type_id') else t.get('name'), 'qty': t.get('qty')} for t in targets],
        'warnings': warnings,
    }
