"""Planetary Interaction profitability engine.

Two concerns, both IO-light and modelled on refining.py/liquidation.py:

* **Static data** — `load_pi_data()` reads the committed data/pi_data.json
  (generated by gen_pi_data.py: the full P0->P4 schematic tree, per-type tier
  metadata, and the planet-type -> P0 mapping) and indexes it for fast lookup.
* **Decision engine** — pure functions that expand a commodity into its full
  recipe tree down to raw P0, and score its profitability. Prices and POCO tax
  rate are passed in by the caller (server.py fetches Jita prices via janice),
  so this module never touches the network — same split as validate.py.

Profit model (self-produced chain, matching evepitool):
  - P0 is extracted from the planet, so it has no ISK purchase cost.
  - Each manufacturing step converts inputs into an output on a factory pin.
  - Moving a produced good off-planet through a Customs Office costs an export
    tax = tax_rate * base_value(type) * quantity, where base_value is CCP's
    reference "adjusted price" (what the game itself taxes on), NOT the market
    price. We charge that export tax once per produced tier in the chain.
  - chain profit / unit = market sell(product) - total POCO export tax.
Per-step margin (buy the direct inputs, make the output, sell it) is reported
alongside so the tool can show both the full-chain and the single-step view.
"""
import json
import os
from functools import lru_cache

DATA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'pi_data.json')

TIER_LABELS = {0: 'P0', 1: 'P1', 2: 'P2', 3: 'P3', 4: 'P4'}


@lru_cache(maxsize=1)
def load_pi_data(path=DATA_PATH):
    """Load + index the static PI dataset. Cached; returns a dict with:

      types        {type_id(int): {name, group_id, tier, volume}}
      schematics   [{schematic_id, name, cycle_time, inputs, outputs}]
      by_output    {output_type_id: schematic}   (PI products are 1:1)
      planet_types (name, ...)
      planet_p0    {planet_type_name: [p0_type_id, ...]}
      p0_ids       frozenset of raw P0 type ids
    """
    with open(path, encoding='utf-8') as f:
        raw = json.load(f)
    types = {int(k): v for k, v in raw['types'].items()}
    schematics = raw['schematics']
    by_output = {}
    for s in schematics:
        for out_id, _qty in s['outputs']:
            by_output[int(out_id)] = s
    planet_p0 = {p: [int(x) for x in ids] for p, ids in raw.get('planet_p0', {}).items()}
    p0_ids = frozenset(tid for tid, v in types.items() if v.get('tier') == 0)
    return {
        'types': types,
        'schematics': schematics,
        'by_output': by_output,
        'planet_types': tuple(raw.get('planet_types', ())),
        'planet_p0': planet_p0,
        'p0_ids': p0_ids,
    }


def type_name(type_id, data=None):
    data = data or load_pi_data()
    t = data['types'].get(int(type_id))
    return t['name'] if t else f'type {type_id}'


def tier_of(type_id, data=None):
    data = data or load_pi_data()
    t = data['types'].get(int(type_id))
    return t.get('tier') if t else None


def producible_ids(data=None, tiers=(1, 2, 3, 4)):
    """Type ids that a factory can make (have a schematic), optionally by tier."""
    data = data or load_pi_data()
    out = []
    for out_id in data['by_output']:
        if data['types'].get(out_id, {}).get('tier') in tiers:
            out.append(out_id)
    return out


def expand_to_p0(product_id, data=None, _seen=None):
    """Return ``{p0_type_id: units}`` — the raw P0 needed to build ONE unit of
    ``product_id`` from scratch, following each schematic's input:output ratio.
    Raises ValueError on a cycle (PI has none, but guard anyway)."""
    data = data or load_pi_data()
    _seen = _seen or ()
    if product_id in _seen:
        raise ValueError(f'schematic cycle at {product_id}')
    sch = data['by_output'].get(int(product_id))
    if not sch:
        return {int(product_id): 1.0}  # already raw (or unknown leaf)
    out_id, out_qty = sch['outputs'][0]
    out_qty = out_qty or 1
    need = {}
    for in_id, in_qty in sch['inputs']:
        per_unit = (in_qty / out_qty)
        for p0, q in expand_to_p0(in_id, data, _seen + (int(product_id),)).items():
            need[p0] = need.get(p0, 0.0) + q * per_unit
    return need


def chain_steps(product_id, data=None):
    """Every manufacturing step in the chain that makes ``product_id``, from the
    deepest P1 up to the final product. Each step: ``{output_id, output_qty,
    inputs:[(id,qty)], tier, schematic_id, cycle_time}``. Deduplicated so a tier
    reused twice in a chain is counted once (matches how you'd run the colony)."""
    data = data or load_pi_data()
    steps = {}

    def walk(pid):
        sch = data['by_output'].get(int(pid))
        if not sch or int(pid) in steps:
            return
        out_id, out_qty = sch['outputs'][0]
        steps[int(pid)] = {
            'output_id': int(out_id),
            'output_qty': int(out_qty),
            'inputs': [(int(i), int(q)) for i, q in sch['inputs']],
            'tier': data['types'].get(int(out_id), {}).get('tier'),
            'schematic_id': sch['schematic_id'],
            'cycle_time': sch['cycle_time'],
        }
        for in_id, _q in sch['inputs']:
            walk(in_id)

    walk(product_id)
    return sorted(steps.values(), key=lambda s: (s['tier'], s['output_id']))


def evaluate(product_id, sell_prices, base_values, tax_rate=0.05, data=None):
    """Score one commodity. Pure. Inputs:

      sell_prices  {type_id: isk}  market sell (Jita) per unit
      base_values  {type_id: isk}  CCP reference price used for POCO tax
      tax_rate     POCO export tax rate (0.05 = 5%)

    Returns a dict with the single-step margin and the full-chain-from-P0 profit,
    all per one unit of ``product_id``. Missing prices are treated as 0 and
    flagged in ``missing_prices``.
    """
    data = data or load_pi_data()
    pid = int(product_id)
    sch = data['by_output'].get(pid)
    if not sch:
        raise ValueError(f'{pid} is not a producible PI commodity')

    def sell(t):
        return float(sell_prices.get(int(t)) or 0)

    def base(t):
        return float(base_values.get(int(t)) or 0)

    out_id, out_qty = sch['outputs'][0]
    out_qty = out_qty or 1
    missing = set()

    # --- single-step margin: buy the direct inputs, make + sell the output ---
    step_input_cost = 0.0
    for in_id, in_qty in sch['inputs']:
        if int(in_id) not in sell_prices:
            missing.add(int(in_id))
        step_input_cost += sell(in_id) * (in_qty / out_qty)
    if pid not in sell_prices:
        missing.add(pid)
    unit_sell = sell(pid)
    step_export_tax = tax_rate * base(pid)  # export the finished unit
    step_margin = unit_sell - step_input_cost - step_export_tax

    # --- full chain from extracted P0 ---
    steps = chain_steps(pid, data)
    # Per unit of final product, how many of each intermediate get produced.
    per_final = _units_per_final(pid, data)
    total_export_tax = 0.0
    for s in steps:
        oid = s['output_id']
        total_export_tax += tax_rate * base(oid) * per_final.get(oid, 0.0)
    p0_need = expand_to_p0(pid, data)
    chain_profit = unit_sell - total_export_tax

    cycle = sch['cycle_time'] or 3600
    return {
        'type_id': pid,
        'name': type_name(pid, data),
        'tier': data['types'].get(pid, {}).get('tier'),
        'tier_label': TIER_LABELS.get(data['types'].get(pid, {}).get('tier')),
        'unit_sell': unit_sell,
        # single-step (make from bought inputs)
        'step_input_cost': step_input_cost,
        'step_export_tax': step_export_tax,
        'step_margin': step_margin,
        # full self-produced chain from free P0
        'chain_export_tax': total_export_tax,
        'chain_profit': chain_profit,
        'p0_need': {int(k): round(v, 4) for k, v in p0_need.items()},
        'p0_units_total': round(sum(p0_need.values()), 2),
        'cycle_time': cycle,
        'missing_prices': sorted(missing),
    }


def _units_per_final(product_id, data):
    """{intermediate_output_id: units produced per 1 final product}, following
    schematic ratios. The final product itself maps to 1.0."""
    data = data or load_pi_data()
    need = {int(product_id): 1.0}

    def walk(pid, mult):
        sch = data['by_output'].get(int(pid))
        if not sch:
            return
        out_id, out_qty = sch['outputs'][0]
        out_qty = out_qty or 1
        for in_id, in_qty in sch['inputs']:
            per = (in_qty / out_qty) * mult
            if data['by_output'].get(int(in_id)):  # intermediate, not raw P0
                need[int(in_id)] = need.get(int(in_id), 0.0) + per
                walk(in_id, per)

    walk(product_id, 1.0)
    return need


def available_products(p0_available, data=None, tiers=(1, 2, 3, 4)):
    """Producible commodities whose ENTIRE chain's raw P0 are all in
    ``p0_available`` (a set of P0 type ids) — i.e. buildable from the planets on
    hand. Returns a list of type ids."""
    data = data or load_pi_data()
    avail = set(int(x) for x in p0_available)
    out = []
    for pid in producible_ids(data, tiers):
        need = expand_to_p0(pid, data)
        if set(need).issubset(avail):
            out.append(pid)
    return out


def rank_chains(p0_available, sell_prices, base_values, tax_rate=0.05,
                data=None, tiers=(1, 2, 3, 4)):
    """Evaluate every commodity buildable from ``p0_available`` and return them
    sorted by full-chain profit per unit, descending."""
    data = data or load_pi_data()
    rows = [evaluate(pid, sell_prices, base_values, tax_rate, data)
            for pid in available_products(p0_available, data, tiers)]
    rows.sort(key=lambda r: r['chain_profit'], reverse=True)
    return rows


if __name__ == '__main__':
    # Self-test against the committed dataset (no network). Verifies chain
    # expansion math with flat unit prices so numbers are hand-checkable.
    d = load_pi_data()
    print(f"types={len(d['types'])} schematics={len(d['schematics'])} "
          f"P0={len(d['p0_ids'])} planets={len(d['planet_p0'])}")
    # Pick a P4 and expand it.
    p4 = [t for t, v in d['types'].items() if v['tier'] == 4]
    pid = sorted(p4)[0]
    print(f"\nP4 sample: {type_name(pid)} ({pid})")
    need = expand_to_p0(pid)
    print("  raw P0 to build 1 unit:")
    for p0, q in sorted(need.items(), key=lambda x: -x[1]):
        print(f"    {q:8.2f} x {type_name(p0)}")
    print(f"  total P0 units: {sum(need.values()):.1f}, steps: {len(chain_steps(pid))}")
    # Evaluate with flat prices (sell=1000 everything, base=100, 5% tax).
    sell = {t: 1000.0 for t in d['types']}
    base = {t: 100.0 for t in d['types']}
    r = evaluate(pid, sell, base)
    print(f"\n  evaluate() with flat sell=1000/base=100/5%: "
          f"chain_profit={r['chain_profit']:.1f} step_margin={r['step_margin']:.1f} "
          f"chain_export_tax={r['chain_export_tax']:.2f}")
